# Generated by Django 4.2.2 on 2023-06-19 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aya', '0003_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='log',
            name='description',
        ),
        migrations.RemoveField(
            model_name='log',
            name='name',
        ),
        migrations.AddField(
            model_name='log',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='log',
            name='details',
            field=models.TextField(default='Event Logged <django.db.models.fields.DateTimeField>', max_length=400),
        ),
        migrations.AddField(
            model_name='log',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='aya.user'),
        ),
        migrations.AddField(
            model_name='log',
            name='event_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='aya.event'),
        ),
    ]
