# Generated by Django 4.2.2 on 2023-06-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aya', '0009_bankaccounttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccounttype',
            name='name',
            field=models.CharField(choices=[('CU', 'Current'), ('SA', 'Savings')], default='CU', unique=True),
        ),
    ]
