# Generated by Django 4.2.2 on 2023-06-19 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aya', '0010_alter_bankaccounttype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('swift_code', models.CharField(max_length=11, unique=True)),
                ('branch_name', models.CharField(max_length=100)),
                ('account_type_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aya.bankaccounttype')),
            ],
        ),
    ]
