# Generated by Django 4.2.2 on 2023-06-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aya', '0011_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(max_length=300)),
            ],
        ),
    ]
