# Generated by Django 4.2.2 on 2023-06-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aya', '0012_paymentcondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(max_length=300)),
                ('cost', models.DecimalField(decimal_places=4, max_digits=6)),
            ],
        ),
    ]
