# Generated by Django 4.2.2 on 2023-06-19 17:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aya', '0014_alter_service_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=10, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=4, max_digits=6)),
                ('issue_date', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField(default=datetime.datetime(2023, 7, 19, 17, 48, 38, 925143, tzinfo=datetime.timezone.utc))),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aya.bank')),
                ('payment_condition_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aya.paymentcondition')),
            ],
        ),
    ]
