# Generated by Django 4.2.2 on 2023-06-19 17:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aya', '0015_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 17, 56, 57, 780466, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=10, unique=True)),
                ('quantity', models.IntegerField(max_length=2)),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aya.invoice')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aya.service')),
            ],
        ),
    ]
