# Generated by Django 4.2.2 on 2023-06-19 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aya', '0019_alter_invoice_due_date_receiptitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arcariusmexen',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='account_type_id',
            new_name='account_type',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='bank_id',
            new_name='bank',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='payment_condition_id',
            new_name='payment_condition',
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='invoice_id',
            new_name='invoice',
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='service_id',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='invoice_id',
            new_name='invoice',
        ),
        migrations.RenameField(
            model_name='receiptitems',
            old_name='invoice_id',
            new_name='invoice',
        ),
        migrations.RenameField(
            model_name='receiptitems',
            old_name='invoice_item_id',
            new_name='invoice_item',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_role_id',
            new_name='user_role',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 18, 17, 32, 542586, tzinfo=datetime.timezone.utc)),
        ),
    ]
